"""initial

Revision ID: 839f48a721d7
Revises: 
Create Date: 2026-02-24 11:45:33.885521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '839f48a721d7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_asset_asset_name'), 'asset', ['asset_name'], unique=False)
    op.drop_index(op.f('ix_facility_facility_name'), table_name='facility')
    op.create_index(op.f('ix_facility_facility_name'), 'facility', ['facility_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_facility_facility_name'), table_name='facility')
    op.create_index(op.f('ix_facility_facility_name'), 'facility', ['facility_name'], unique=False)
    op.drop_index(op.f('ix_asset_asset_name'), table_name='asset')
    # ### end Alembic commands ###
